#!/usr/bin/env python3
"""Copy LibOSDP into components/osdp_cp as flat, prefixed source files.

ESPHome only compiles files sitting directly in an external component's
folder, so LibOSDP's tree is flattened and every file is prefixed with
``libosdp_`` to avoid clashing with other headers (FreeRTOS has a queue.h,
for example). Includes are rewritten to match, and __BARE_METAL__ is defined
at the top of each file so no global build flag is needed.

Usage:
    git clone --recurse-submodules -b v3.2.7 https://github.com/goToMain/libosdp
    python3 tools/vendor_libosdp.py path/to/libosdp
"""

from pathlib import Path
import re
import shutil
import sys

DEST = Path(__file__).resolve().parent.parent / "components" / "osdp_cp"

# (source path relative to the LibOSDP checkout, flat destination name)
FILES = [
    ("include/osdp.h", "libosdp.h"),
    ("include/osdp_export.h", "libosdp_export.h"),
    ("platformio/osdp_config.h", "libosdp_config.h"),
    ("src/osdp_common.h", "libosdp_common.h"),
    ("src/osdp_file.h", "libosdp_file.h"),
    ("src/osdp_diag.h", "libosdp_diag.h"),
    ("src/osdp_common.c", "libosdp_common.c"),
    ("src/osdp_cp.c", "libosdp_cp.c"),
    ("src/osdp_pd.c", "libosdp_pd.c"),
    ("src/osdp_phy.c", "libosdp_phy.c"),
    ("src/osdp_sc.c", "libosdp_sc.c"),
    ("src/osdp_file.c", "libosdp_file.c"),
    ("src/crypto/tinyaes.c", "libosdp_tinyaes.c"),
    ("src/crypto/tinyaes_src.c", "libosdp_tinyaes_src.c"),
    ("src/crypto/tinyaes_src.h", "libosdp_tinyaes_src.h"),
]
UTILS = ["utils", "queue", "list", "slab", "logger", "disjoint_set", "crc16", "assert"]
UTILS_SRC = ["utils", "queue", "list", "slab", "logger", "disjoint_set", "crc16"]
FILES += [(f"utils/include/utils/{u}.h", f"libosdp_u_{u}.h") for u in UTILS]
FILES += [(f"utils/src/{u}.c", f"libosdp_u_{u}.c") for u in UTILS_SRC]

# include target as written in the sources -> new flat name
INCLUDE_MAP = {
    "osdp.h": "libosdp.h",
    "osdp_export.h": "libosdp_export.h",
    "osdp_config.h": "libosdp_config.h",
    "osdp_common.h": "libosdp_common.h",
    "osdp_file.h": "libosdp_file.h",
    "osdp_diag.h": "libosdp_diag.h",
    "tinyaes_src.h": "libosdp_tinyaes_src.h",
    **{f"utils/{u}.h": f"libosdp_u_{u}.h" for u in UTILS},
}

# LibOSDP's bundled utils/tinyAES export generic C names (list_init, queue_init,
# AES_ECB_encrypt, get_time...). Rename them so they can't collide with ESP-IDF
# or other components at link time. Public headers are left alone so these
# macros never leak into ESPHome code.
SYMBOLS = """
AES_CBC_decrypt_buffer AES_CBC_encrypt_buffer AES_CTR_xcrypt_buffer AES_ECB_decrypt
AES_ECB_encrypt AES_ctx_set_iv AES_init_ctx AES_init_ctx_iv __logger_log
add_iso8601_utc_datetime crc16_itu_t default_logger disjoint_set_find
disjoint_set_make disjoint_set_num_roots disjoint_set_union dump_trace get_time
hexdump list_append list_appendleft list_check_links list_find_node list_init
list_insert_node list_insert_nodes list_pop list_popleft list_remove_node
list_remove_nodes logger_get_default logger_init logger_set_default
logger_set_file logger_set_log_level logger_set_name logger_set_put_fn
millis_now millis_since num_digits_in_number queue_dequeue queue_enqueue
queue_init queue_peek_first queue_peek_last rand_u32 randint round_up_pow2
slab_alloc slab_free slab_init slist_append slist_appendleft slist_init
slist_insert_node slist_pop slist_popleft slist_remove_node usec_now usec_since
""".split()
PUBLIC = {"libosdp.h", "libosdp_export.h", "libosdp_config.h"}

INCLUDE_RE = re.compile(r'#include\s*[<"]([^>"]+)[>"]')
HEADER = (
    "/* Vendored from LibOSDP v3.2.7 (Apache-2.0) by tools/vendor_libosdp.py */\n"
    "#ifndef __BARE_METAL__\n#define __BARE_METAL__\n#endif\n"
)


def symbols_header() -> str:
    lines = ["/* Generated by tools/vendor_libosdp.py: private symbol prefixes */",
             "#pragma once"]
    lines += [f"#define {sym} libosdp_priv_{sym.lstrip('_')}" for sym in SYMBOLS]
    return "\n".join(lines) + "\n"


# Config tweaks for a single-reader door controller.
CONFIG_PATCHES = {
    # Retry an offline reader every 30 s instead of every 5 minutes.
    "#define OSDP_ONLINE_RETRY_WAIT_MAX_MS           (300 * 1000u)":
    "#define OSDP_ONLINE_RETRY_WAIT_MAX_MS           (30 * 1000u)",
}


def rewrite(text: str, name: str) -> str:
    def repl(m: re.Match) -> str:
        target = m.group(1)
        if target in INCLUDE_MAP:
            return f'#include "{INCLUDE_MAP[target]}"'
        return m.group(0)

    header = HEADER
    if name not in PUBLIC:
        header += '#include "libosdp_symbols.h"\n'
    if name == "libosdp_config.h":
        for old, new in CONFIG_PATCHES.items():
            if old not in text:
                sys.exit(f"config patch no longer applies: {old}")
            text = text.replace(old, new)
    return header + INCLUDE_RE.sub(repl, text)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = Path(sys.argv[1])
    for old in DEST.glob("libosdp_*"):
        old.unlink()
    for old in DEST.glob("libosdp.h"):
        old.unlink()
    for rel, name in FILES:
        text = (src / rel).read_text(encoding="utf-8")
        (DEST / name).write_text(rewrite(text, name), encoding="utf-8")
    (DEST / "libosdp_symbols.h").write_text(symbols_header(), encoding="utf-8")
    shutil.copy(src / "LICENSE", DEST / "LIBOSDP_LICENSE")
    print(f"Vendored {len(FILES) + 1} files into {DEST}")


if __name__ == "__main__":
    main()
